// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg5p59zpr13A1eu_w2EKHz9pCP__LGNBw',
    appId: '1:674943133372:android:c97f0ca9f016afcd5a52b9',
    messagingSenderId: '674943133372',
    projectId: 'billingapp-6e9dc',
    storageBucket: 'billingapp-6e9dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAip-jDZq9e-J4StNPZdAsYprFu7T5iKhI',
    appId: '1:674943133372:ios:854552a354ab52655a52b9',
    messagingSenderId: '674943133372',
    projectId: 'billingapp-6e9dc',
    storageBucket: 'billingapp-6e9dc.appspot.com',
    iosBundleId: 'com.example.billingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6tMglsY8oGUGPKCMtiBMOwdYSSvyhzr8',
    appId: '1:674943133372:web:22f30bf9c2cf03375a52b9',
    messagingSenderId: '674943133372',
    projectId: 'billingapp-6e9dc',
    authDomain: 'billingapp-6e9dc.firebaseapp.com',
    storageBucket: 'billingapp-6e9dc.appspot.com',
  );
}
